language: node_js
node_js:
  - 6
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g node-gyp
  - yarn
script:
  - npm run test